Name:           ros-hydro-segbot-sensors
Version:        0.3.0
Release:        0%{?dist}
Summary:        ROS segbot_sensors package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/segbot_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       pyserial
Requires:       ros-hydro-camera1394
Requires:       ros-hydro-depthimage-to-laserscan
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-filters
Requires:       ros-hydro-freenect-launch
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-hokuyo-node
Requires:       ros-hydro-laser-filters
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-openni-launch
Requires:       ros-hydro-pcl-ros
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rviz
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-smart-battery-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
Requires:       ros-hydro-tf2-ros
Requires:       ros-hydro-urg-node
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-laser-filters
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-pcl-ros
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-roslaunch
BuildRequires:  ros-hydro-roslint
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-smart-battery-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
Contains sensor specific launch files and all the relevant filters that are
applied on sensor data before being used by the segbot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sat Mar 14 2015 Piyush Khandelwal <piyushk@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

