<?xml version="1.0"?>

<root
  xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <include filename="$(find segbot_description)/gazebo/common.gazebo.xacro" />

  <xacro:macro name="segbot_base_link_collision" >
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://segbot_description/meshes/rmp50-base-link.dae" scale="0.0254 0.0254 0.0254"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="segbot_castor_support_link_collision" >
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://segbot_description/meshes/rmp50-castor-link.dae" scale="0.0254 0.0254 0.0254"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="segbot_castor_wheel_link_collision" >
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://segbot_description/meshes/rmp50-castor-wheel.dae" scale="0.0254 0.0254 0.0254"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="segbot_wheel_collision" params="suffix">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://segbot_description/meshes/rmp50-${suffix}-wheel.dae" scale="0.0254 0.0254 0.0254"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="segbot_battery_box_collision">
    <collision>
      <origin xyz="0 0 ${5.5*INCH_TO_M}" rpy="0 0 0"/>
      <geometry>
        <box size="${7*INCH_TO_M} ${14*INCH_TO_M} ${11*INCH_TO_M}" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="laptop_collision">
    <collision>
      <origin xyz="0 0 ${0.375*INCH_TO_M}" rpy="0 0 0"/>
      <geometry>
        <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="laptop_screen_collision">
    <collision>
      <origin xyz="${6*INCH_TO_M} 0 -${0.375*INCH_TO_M}" rpy="0 0 0"/>
      <geometry>
        <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="aluminium_sheet_collision" params="thickness length width">
    <collision>
      <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${thickness}" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="beam_8020_collision" params="length">
    <collision>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${1*INCH_TO_M} ${1*INCH_TO_M} ${length}" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="standoff_632_collision" params="length">
    <collision>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length}" radius="0.003175" />
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_ros_controllers">
    <gazebo>
      <xacro:gazebo_segbot_drive_plugin update_rate="100" />
      <!-- <xacro:gazebo_segbot_controllers_common /> -->
    </gazebo>
  </xacro:macro>

</root>

