<?xml version="1.0"?>

<robot name="segbot"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <include filename="$(find segbot_description)/urdf/common.urdf.xacro" />
  <include filename="$(find segbot_description)/gazebo/full_collision.gazebo.xacro" />
  <include filename="$(find segbot_description)/urdf/segbot_base.urdf.xacro" />
  <include filename="$(find segbot_description)/urdf/segbot_chassis.urdf.xacro" />
  <include filename="$(find segbot_description)/urdf/mounts/hokuyo_mount.urdf.xacro" />

  <!-- Add the segbot base -->
  <xacro:segbot />
  <xacro:segbot_chassis parent="base">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}"/>
  </xacro:segbot_chassis>

  <!-- Add the hokuyo -->
  <xacro:hokuyo_mount name="nav_hokuyo" parent="front_left_vertical_beam" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}" ros_topic="scan" update_rate="10" min_angle="${-(5 * M_PI)/12}" max_angle="${(5 * M_PI)/12}">
    <origin xyz="0 -${0.5*INCH_TO_M} ${6*INCH_TO_M}" rpy="${M_PI/2} ${M_PI/2} 0" />
  </xacro:hokuyo_mount>

  <xacro:gazebo_segbot_ros_controllers />

</robot>
