<?xml version="1.0"?>

<robot name="segbot"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find segbot_description)/urdf/v2/common.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/gazebo/segbot.gazebo.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/segbot_base.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/v2/segbot_chassis.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/mounts/hokuyo_mount.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/mounts/kinect_mount.urdf.xacro" />

  <!-- Add the segbot base -->
  <xacro:segbot />
  <xacro:segbot_chassis parent="base">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}"/>
  </xacro:segbot_chassis>

  <!-- Add the forward facing kinect sensor for navigation -->
  <xacro:kinect_mount name="nav_kinect" parent="back_right_vertical_beam" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}">
    <origin xyz="${1*INCH_TO_M} -${0.5*INCH_TO_M} ${11.5*INCH_TO_M}" rpy="-${M_PI/2} -${M_PI/2} 0" />
  </xacro:kinect_mount>

  <!-- Add the hokuyo -->
  <xacro:hokuyo_mount name="nav_hokuyo" parent="front_left_vertical_beam" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}" ros_topic="scan" update_rate="10" min_angle="${-(5 * M_PI)/12}" max_angle="${(5 * M_PI)/12}">
    <origin xyz="${1*INCH_TO_M} ${0.5*INCH_TO_M} ${4.5*INCH_TO_M}" rpy="${M_PI/2} ${M_PI/2} 0" />
  </xacro:hokuyo_mount>

  <!-- The sensor plate shares the hokuyo mount. Use the beam generated by the hokuyo mount to generate the sensor
       plate. -->
  <xacro:standoff name="left_sensor_plate_standoff" parent="nav_hokuyo_sensor_beam" length="${0.5*INCH_TO_M}" radius="${0.25*INCH_TO_M}">
    <origin xyz="-${1/2*INCH_TO_M} 0 ${3.5*INCH_TO_M}" rpy="-${M_PI/2} 0 ${M_PI/2}" />
  </xacro:standoff>
  <xacro:standoff name="right_sensor_plate_standoff" parent="nav_hokuyo_sensor_beam" length="${0.5*INCH_TO_M}" radius="${0.25*INCH_TO_M}">
    <origin xyz="-${1/2*INCH_TO_M} 0 ${8.5*INCH_TO_M}" rpy="-${M_PI/2} 0 ${M_PI/2}" />
  </xacro:standoff>
  <xacro:aluminium_sheet name="sensor_plate" parent="left_sensor_plate_standoff" thickness="0.003" length="${4.5*INCH_TO_M}" width="${9*INCH_TO_M}">
    <origin xyz="-${1/4*INCH_TO_M} -${2.5*INCH_TO_M} ${1/2*INCH_TO_M}" rpy="0 0 0" />
  </xacro:aluminium_sheet>

  <joint name="sonar_center_joint" type="fixed">
    <origin xyz="-${8.58*INCH_TO_M} 0 ${0.003 + 0.012}" />
    <parent link="sensor_plate_link"/>
    <child link="sonar_center_link"/>
  </joint>
  <!-- sonar_center_link is an empty link that marks the start -->
  <link name="sonar_center_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <!-- sonar0 - right -->
  <joint name="sonar0_rotated_center_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 -${M_PI/9}"/>
    <parent link="sonar_center_link"/>
    <child link="sonar0_rotated_center_link"/>
  </joint>
  <link name="sonar0_rotated_center_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <joint name="sonar0_joint" type="fixed">
    <origin xyz="${10.33*INCH_TO_M} 0 0" />
    <parent link="sonar0_rotated_center_link"/>
    <child link="sonar0_link"/>
  </joint>
  <link name="sonar0_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.012 0.044 0.023" />
      </geometry>
    </visual>
  </link>

  <!-- sonar1 - center -->
  <joint name="sonar1_joint" type="fixed">
    <origin xyz="${10.33*INCH_TO_M} 0 0" />
    <parent link="sonar_center_link"/>
    <child link="sonar1_link"/>
  </joint>
  <link name="sonar1_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.012 0.044 0.023" />
      </geometry>
    </visual>
  </link>

  <!-- sonar2 - left -->
  <joint name="sonar2_rotated_center_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${M_PI/9}"/>
    <parent link="sonar_center_link"/>
    <child link="sonar2_rotated_center_link"/>
  </joint>
  <link name="sonar2_rotated_center_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <joint name="sonar2_joint" type="fixed">
    <origin xyz="${10.33*INCH_TO_M} 0 0" />
    <parent link="sonar2_rotated_center_link"/>
    <child link="sonar2_link"/>
  </joint>
  <link name="sonar2_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
        iyy="0.01"  iyz="0.0"
        izz="0.01" />
    </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.012 0.044 0.023" />
      </geometry>
    </visual>
  </link>

  <!-- Add a beam at top so that the robot looks complete. We'll probably have a different sensor mount here eventually. -->
  <xacro:beam_8020 name="front_cap_beam" parent="front_right_vertical_beam" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}">
    <origin xyz="0 -${0.5*INCH_TO_M} ${36.5*INCH_TO_M}" rpy="-${M_PI/2} 0 0" />
  </xacro:beam_8020>

  <xacro:gazebo_segbot_ros_controllers />

</robot>
