<?xml version="1.0"?>

<robot name="segbot"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <include filename="$(find segbot_description)/urdf/common.urdf.xacro" />
  <include filename="$(find segbot_description)/gazebo/full_collision.gazebo.xacro" />
  <include filename="$(find segbot_description)/urdf/segbot_base.urdf.xacro" />
  <include filename="$(find segbot_description)/urdf/segbot_chassis.urdf.xacro" />
  <include filename="$(find segbot_description)/urdf/mounts/kinect_mount.urdf.xacro" />

  <!-- Add the segbot base -->
  <xacro:segbot />
  <xacro:segbot_chassis parent="base">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}"/>
  </xacro:segbot_chassis>

</robot>
