<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
      xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find segbot_description)/urdf/components/beam_8020.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/standoff.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/aluminium_sheet.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/sensors/hokuyo_04lx_laser.urdf.xacro" />

  <xacro:macro name="hokuyo_mount" params="name parent *origin length ros_topic update_rate min_angle max_angle">
    <xacro:beam_8020 name="${name}_sensor_beam" parent="${parent}" length="${length}">
      <xacro:insert_block name="origin" />
    </xacro:beam_8020>
    <xacro:aluminium_sheet name="${name}_plate" parent="${name}_sensor_beam" 
                          thickness="${0.125*INCH_TO_M}" length="0.06" width="0.12">
                           <origin xyz="${0.5*INCH_TO_M} 0 ${length/2}" rpy="${M_PI/2} 0 ${M_PI/2}" />
    </xacro:aluminium_sheet>

    <xacro:hokuyo_04lx_laser name="${name}" parent="${name}_plate" ros_topic="${ros_topic}" update_rate="${update_rate}" min_angle="${min_angle}" max_angle="${max_angle}">
      <origin xyz="0 0 ${0.125*INCH_TO_M}" rpy="0 0 0" />
    </xacro:hokuyo_04lx_laser>

  </xacro:macro>

</root>


